### ISSUE TITLE
Update My NFTs Empty View

### ISSUE THREAD

**Issue by earth2travis** [FraktalNFT/projects#51]
## View Name

https://fraktal-dapp.vercel.app/my-nfts

## Description

When user connects wallet and clicks on wallet button this is the view they will see

### As-is

![as-is](https://user-images.githubusercontent.com/522182/136608858-da84556b-a8fd-481f-80cc-d5fde6b20619.png)

### Desired

![desired](https://user-images.githubusercontent.com/522182/136628791-6a4d9491-24d6-4783-8db2-c3ff267534d2.png)

## Link to Figma Frame

https://www.figma.com/file/n7fGvM4lFZuUsUcOcOXlBc/Fraktal-App-|-Raid-Guild?node-id=344%3A3061

## ToDo

- [ ] Add Your Fraktal NFTs Component from [Issue #56](https://github.com/FraktalNFT/projects/issues/56)
- [ ] Add Your Fraktions Component from [Issue #57](https://github.com/FraktalNFT/projects/issues/57)
- [ ] Your Wallet NFTs Component from [Issue #58](https://github.com/FraktalNFT/projects/issues/58)

**Comment by nickcaputo** [comment]
Created pull request https://github.com/FraktalNFT/dapp-frontend/pull/39

All in line with the Figma!

**Comment by earth2travis** [comment]
Seems like the Your Fraktions section is missing the grey box and text:

Current:
![image](https://user-images.githubusercontent.com/522182/142885916-a1b5194c-7e82-45f3-9554-c945f1d2d779.png)

Desired:
![image](https://user-images.githubusercontent.com/522182/142886008-794c974a-4d78-4a06-b73f-a89058817e6f.png)

- [ ] Add text, "Head over to the Marketplace and invest to get some Fraktions! 
If you have already invested, contributions do not appear until the auctions are over." with Marketplace link
- [ ] Add Back to Marketplace button
- [ ] Add Claim All button in the Claim Your Sold Fraktions section

**Comment by nickcaputo** [comment]
I will add the Claim All button and get that up and running.  Strange, when I first made the PR it was definitely showing the aforementioned grey box, tested and all.  Should that be an issue with vercel?  But in any event, it looks good so far

**Comment by nickcaputo** [comment]
Small thing, on the "Claim all" button in My-NFTs, I have the following function to call:

                  onClick={()=>rescueEth(provider, marketAddress)}


Should I be entering anything else?  Effectively, this would make the new "Claim all" and existing "Claim" buttons do the exact same thing.  The "Claim" button appears only when there is claimable ETH from sold fraktions, the "Claim all" button would appear all the time.

@sascha @earth2travis do you think we should scrap the "Claim all" button in this case?
