### ISSUE TITLE
Create Your Fraktal NFTs Component

### ISSUE THREAD

**Issue by earth2travis** [FraktalNFT/projects#56]
## View Name

https://fraktal-dapp.vercel.app/my-nfts

## Description

Display NFTs that have been minted or imported on the Fraktal protocol

### No NFTs

![no-nfts](https://user-images.githubusercontent.com/522182/136625833-8fc4d01f-3e75-435e-b6af-8a85fcfb6682.png)

### Your Fraktal NFTs

![your-fraktal-nfts](https://user-images.githubusercontent.com/522182/136625960-a2424c36-1431-440a-b858-5d2b9b9d8c5f.png)

## Link to Figma Frame

- [No NFTs](https://www.figma.com/file/n7fGvM4lFZuUsUcOcOXlBc/Fraktal-App-|-Raid-Guild?node-id=344%3A3061)
- [Your Fraktal NFTs](https://www.figma.com/file/n7fGvM4lFZuUsUcOcOXlBc/Fraktal-App-|-Raid-Guild?node-id=343%3A529)

## ToDo

- [x] Change heading "My NFTs" to "Your NFTs"
- [x] Left align headings and make size consistent
- [ ] Add Sort drop-down
- [x] Change button text from "Mint NFT" to "Add NFT"
- [x] Right align "Add NFT" button
- [x] Add grey rectangle under "Your NFTs" with the following text "You do not have any NFTs. Mint or Import a new NFT."
- [x] Add link to "Mint or Import"
- [x] Display NFTs that have been minted or imported on the Fraktal protocol

**Comment by mackbowes** [comment]
Estimate: 1.5 hours

**Comment by mackbowes** [comment]
blocked by broken subgraph

**Comment by mackbowes** [comment]
Tabled Dropdown sorting for now
