### ISSUE TITLE
Create Your Fraktions Component

### ISSUE THREAD

**Issue by earth2travis** [FraktalNFT/projects#57]
## View Name

https://fraktal-dapp.vercel.app/my-nfts

## Description

Display NFTs that the user owns a percentage of

### No Fraktions

![no-fraktions](https://user-images.githubusercontent.com/522182/136627022-dade033d-5dec-4df6-a046-4cf738997b30.png)

### Fraktions

![fraktions](https://user-images.githubusercontent.com/522182/136627125-281777a3-e5c3-419d-acc5-5ca9aef42875.png)

## Link to Figma Frames

- [No Fraktions](https://www.figma.com/file/n7fGvM4lFZuUsUcOcOXlBc/Fraktal-App-|-Raid-Guild?node-id=344%3A3061)
- [Fraktions](https://www.figma.com/file/n7fGvM4lFZuUsUcOcOXlBc/Fraktal-App-|-Raid-Guild?node-id=343%3A529)

## ToDo

- [x] Change heading "My Fraktions" to "Your Fraktions"
- [x] Add grey rectangle under "Your Fraktions" with the following text "Head over to the Marketplace and invest to get some Fraktions! If you have already invested, contributions do not appear until the auctions are over."
- [x] Link "Marketplace" to Marketplace
- [x] Add Back to Marketplace button
- [x] Add Claim Your Sold Fraktions Component from [Issue #53](https://github.com/FraktalNFT/projects/issues/53)

**Comment by earth2travis** [comment]
Difficult to access this application state. Should be sum of all revenue. Can only been claimed at once. Balance of account in market contract.

**Comment by mackbowes** [comment]
This was also done.
