### ISSUE TITLE
Create Your Wallet NFTs Component

### ISSUE THREAD

**Issue by earth2travis** [FraktalNFT/projects#58]
## View Name

https://fraktal-dapp.vercel.app/my-nfts

## Description

Display all NFTs that the user has in their connected wallet

### No NFTs

![no-nfts](https://user-images.githubusercontent.com/522182/136627890-49e3f24a-68e2-4b0e-9115-ee35a7aa0eec.png)

### Your Wallet NFTs

![your-wallet-nfts](https://user-images.githubusercontent.com/522182/136627952-a1a60988-31db-4f8a-bccf-405c651908a9.png)

## Link to Figma Frame

- [No NFTs](https://www.figma.com/file/n7fGvM4lFZuUsUcOcOXlBc/Fraktal-App-|-Raid-Guild?node-id=344%3A3061)
- [Your Wallet NFTs](https://www.figma.com/file/n7fGvM4lFZuUsUcOcOXlBc/Fraktal-App-|-Raid-Guild?node-id=343%3A529)

## ToDo

- [x] Add "Your Wallet NFTs" heading
- [x] Add grey rectangle under with the following text "No NFTs in Your Wallet."
- [x] Add "Import" button that links to mint/import
- [x] Display ERC-721 or ERC-1155 NFTs that the user has in their connected wallet

**Comment by mackbowes** [comment]
Time estimate: 1-3 hours (sorry)

**Comment by mackbowes** [comment]
I opened main to review this ticket and it was mostly already done. Rewrote some conditional logic.
