### ISSUE TITLE
Update header and footer navigation

### ISSUE THREAD

**Issue by earth2travis** [FraktalNFT/projects#67]
## View Name

All dApp views

## Description

Implement updated styles and states

## ToDo 

- [x] Update logo (link to: https://www.fraktal.io/)
- [x] Update wallet button
- [x] Update top navigation menu buttons
- [x] Change text in footer

### Current

![current-header](https://user-images.githubusercontent.com/522182/137543510-2b5f98e5-a4e0-4737-ac1b-23394b12e779.png)

### Desired

![desired-header](https://user-images.githubusercontent.com/522182/137543723-6ad77279-0a64-4797-89b5-dc75bf35bf96.png)

## Link to Figma Frame

- [Button](https://www.figma.com/file/n7fGvM4lFZuUsUcOcOXlBc/Fraktal-App-|-Raid-Guild?node-id=1017%3A49995)
- [Menu Buttons](https://www.figma.com/file/n7fGvM4lFZuUsUcOcOXlBc/Fraktal-App-|-Raid-Guild?node-id=1017%3A17742)
- [Header](https://www.figma.com/file/n7fGvM4lFZuUsUcOcOXlBc/Fraktal-App-|-Raid-Guild?node-id=3%3A1177)
- [Footer](https://www.figma.com/file/n7fGvM4lFZuUsUcOcOXlBc/Fraktal-App-|-Raid-Guild?node-id=4%3A3)

**Comment by nickcaputo** [comment]
With the header in Figma, it requires the Twitter, Discord and Medium icons to be in the header also, but with the current side margins we had, it was almost too condensed it seemed like:
<img width="1031" alt="Screen Shot 2021-11-06 at 1 25 46 PM" src="https://user-images.githubusercontent.com/13974846/140620048-230dfb40-b8f4-4d38-9ecb-0b87a10e2618.png">


I experimented with making it a bit wider, the header.  @smombartz @earth2travis what do you think of this option?  It is in the PR


<img width="1385" alt="Screen Shot 2021-11-06 at 1 26 04 PM" src="https://user-images.githubusercontent.com/13974846/140620062-d107aa9a-07f3-4150-bf67-85eb38ed2aad.png">

**Comment by nickcaputo** [comment]
Also, the footer removed the copyright information, should we put it back in?
<img width="532" alt="Screen Shot 2021-11-06 at 1 28 05 PM" src="https://user-images.githubusercontent.com/13974846/140620096-976a3714-9dd3-4d90-b994-c4afaf4364b5.png">
