### ISSUE TITLE
Update 404 Error Page

### ISSUE THREAD

**Issue by earth2travis** [FraktalNFT/projects#68]
## View Name

- 404

## Description

Update design and text of 404 error page

## ToDo

- [x] Add grey box for background
- [x] Add leaf image
- [x] Update text styles
- [x] Update button styles

### Current

![current-404](https://user-images.githubusercontent.com/522182/137544089-426b5b7e-d2a3-4f68-9ea6-6f6c396eee93.png)

### Desired

![desired-404](https://user-images.githubusercontent.com/522182/137544155-1924500f-d3f8-4ed0-b2c3-87571572dbd1.png)

## Link to Figma Frame

- [404](https://www.figma.com/file/n7fGvM4lFZuUsUcOcOXlBc/Fraktal-App-|-Raid-Guild?node-id=1075%3A6701)
